### ISSUE TITLE
hinting of the letter "p" freetype 2.10 vs. freetype 2.12

### ISSUE THREAD

**Issue by Golddouble** [maximilionus/freetype-envision#2]
I also do not like Antialiasing since it was introduced in Windows Vista. Now I am in Linux and do still not like Antialiasing. But I do also not like the grey shadow rendering. In Debian 10 I have made the wohle system free of theses techniques and have used "Arial".

This is what I had in my Debian 10 based System (please click on it and look at it at zoom 100%):
![grafik](https://github.com/maximilionus/freetype-envision/assets/13977359/ae91bd84-32fc-4c63-b137-f6f0b240482e)

Now I have changed to Debian 12. So now it has also changed the freetype version. It was version 2.10 in Debian 10 and now it is 2.12 in Debian 12. And now the hinting in Freetype 2.12 has deteriorated. Please pay attention to the small letter "p". This is how it looks now in Debian 12 (please click on it and look at it at zoom 100%):
![grafik](https://github.com/maximilionus/freetype-envision/assets/13977359/36568255-d7f7-4fba-831e-67ee202a9e5f)

This is an ugly "p".

And now enlarged:
Debian 10:
![grafik](https://github.com/maximilionus/freetype-envision/assets/13977359/b32f91d0-adf9-4ef0-ac61-1c717fc0d9ac)

Debian 12:
![grafik](https://github.com/maximilionus/freetype-envision/assets/13977359/15377d1a-e3a0-47cf-bb05-6e4fa5f2cdad)

But I also don't like it with shadows (it's blurry):
![grafik](https://github.com/maximilionus/freetype-envision/assets/13977359/f1d4ca64-35c0-49c4-b240-b84352df79fa)

Is there a way, to change the hinting of this single pixel of the letter "p"?
Or is this project only concerned with the grey shadows?

Thank you.

**Comment by maximilionus** [comment]
**Hi.**

## About "p"
Yes, this issue exist even on my configuration _(Fedora 39, Gnome 45, FreeType 2.13)_ with some fonts, like the default Gnome **Cantarell** for example, but is is less visible because of the antialiasing applied:
![Screenshot from 2024-03-24 23-34-23](https://github.com/maximilionus/freetype-envision/assets/29492157/21ac44a3-4cf4-4734-8993-4e81f59bd056)

I believe the only way to solve this problem is to disable the font hinting completely, but this **will** make the fonts less clear. You can do so:
- In **gnome-tweaks** (Fonts - Hinting - Set to None).
- If the first one doesn't disable hinting completely, enforce it with a fontconfig rule:
  ```sh
  # Change directory to the system fontconfig entries location
  $ cd /etc/fonts/conf.d
 
  # Disable hinting
  $ sudo rm 10-hinting-slight.conf
  $ sudo ln -s /usr/share/fontconfig/conf.avail/10-hinting-none.conf

  # Revert the changes if you don't like them
  $ sudo rm 10-hinting-none.conf
  $ sudo ln -s /usr/share/fontconfig/conf.avail/10-hinting-slight.conf
  ```

## The goal of this project
I really don't want to start yet another holy war about fonts antialiasing, but I personally prefer this feature to be on, as it makes fonts look beautiful. So I see my goal in making the **grayscale** antialiasing with optional **hinting** look good on any monitor, not just the HiDPI ones.

Now I am faced with a choice of which way to take the project. Whether to keep it exclusively as a command-line utility with automated installation through the package manager or as an application with a full-fledged graphical interface, where the user can choose from a list of pre-defined presets with the possibility to switch to the advanced mode, where he can make all the settings himself.

**Comment by maximilionus** [comment]
If there are no more questions, I will close this issue for now.
